# src/AppMatrix/MatrixBundle/Resources/config/routing.yml
AppMatrixMatrixBundle_homepage:
    path:     /
    defaults: { _controller: "AppMatrixMatrixBundle:Index:index" }
    requirements:
         methods:  GET|POST

AppMatrixMatrixBundle_about:
    path:     /about
    defaults: { _controller: "AppMatrixMatrixBundle:About:about" }
    requirements:
         methods:  GET
AppMatrixMatrixBundle_form:
    path:  /form
    defaults: { _controller: "AppMatrixMatrixBundle:Page:form" }
    requirements:
        methods:  GET|POST
AppMatrixMatrixBundle_project_form:
    path:  /{id}/form
    methods:  ['GET', 'POST']
    defaults: { _controller: "AppMatrixMatrixBundle:Page:form" }
    requirements:
       #id:  '\d+'
AppMatrixMatrixBundle_calculation:
    path:  /{id}/calculation
    methods:  ['GET', 'POST']
    defaults: { _controller: "AppMatrixMatrixBundle:Calculation:calculation" }
    requirements:
       #id:  '\d+'
